In [3]:
import pandas as pd

In [18]:
DP_LIVE_02_df = pd.read_csv("DP_LIVE_02.csv")

In [19]:
DP_LIVE_02_df

,Unnamed: 0,Unnamed: 0.1,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,0,0,AUS,HEALTHEXP,TOT,USD_CAP,A,2016,4624.966,D
1,1,1,AUT,HEALTHEXP,TOT,USD_CAP,A,2016,5195.531,NaN
2,2,2,BEL,HEALTHEXP,TOT,USD_CAP,A,2016,5003.902,NaN
3,3,3,CAN,HEALTHEXP,TOT,USD_CAP,A,2016,5039.601,NaN
4,4,4,CZE,HEALTHEXP,TOT,USD_CAP,A,2016,2670.970,NaN
...,...,...,...,...,...,...,...,...,...,...
603,603,603,EST,HEALTHEXP,VOLUNTARY,USD_CAP,A,2020,642.927,P
604,604,604,LTU,HEALTHEXP,COMPULSORY,USD_CAP,A,2020,1952.087,P
605,605,605,LTU,HEALTHEXP,VOLUNTARY,USD_CAP,A,2020,987.903,P
606,606,606,SVN,HEALTHEXP,COMPULSORY,USD_CAP,A,2020,2882.089,P
607,607,607,SVN,HEALTHEXP,VOLUNTARY,USD_CAP,A,2020,901.064,P

In [21]:
DP_LIVE_02_2020_df=DP_LIVE_02_df[DP_LIVE_02 ['TIME']!=2020]
DP_LIVE_02_2020_df

,Unnamed: 0,Unnamed: 0.1,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,0,0,AUS,HEALTHEXP,TOT,USD_CAP,A,2016,4624.966,D
1,1,1,AUT,HEALTHEXP,TOT,USD_CAP,A,2016,5195.531,NaN
2,2,2,BEL,HEALTHEXP,TOT,USD_CAP,A,2016,5003.902,NaN
3,3,3,CAN,HEALTHEXP,TOT,USD_CAP,A,2016,5039.601,NaN
4,4,4,CZE,HEALTHEXP,TOT,USD_CAP,A,2016,2670.970,NaN
...,...,...,...,...,...,...,...,...,...,...
555,555,555,HRV,HEALTHEXP,VOLUNTARY,USD_CAP,A,2019,364.424,NaN
556,556,556,CYP,HEALTHEXP,COMPULSORY,USD_CAP,A,2019,1537.815,NaN
557,557,557,CYP,HEALTHEXP,VOLUNTARY,USD_CAP,A,2019,1184.417,NaN
558,558,558,ROU,HEALTHEXP,COMPULSORY,USD_CAP,A,2019,1524.456,NaN
559,559,559,ROU,HEALTHEXP,VOLUNTARY,USD_CAP,A,2019,370.561,NaN

In [22]:
DP_LIVE_02_2019_df=DP_LIVE_02_2020_df[DP_LIVE_02 ['TIME']!=2019]
DP_LIVE_02_2019_df

<ipython-input-22-442ad64caa9a>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  DP_LIVE_02_2019_df=DP_LIVE_02_2020_df[DP_LIVE_02 ['TIME']!=2019]

,Unnamed: 0,Unnamed: 0.1,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,0,0,AUS,HEALTHEXP,TOT,USD_CAP,A,2016,4624.966,D
1,1,1,AUT,HEALTHEXP,TOT,USD_CAP,A,2016,5195.531,NaN
2,2,2,BEL,HEALTHEXP,TOT,USD_CAP,A,2016,5003.902,NaN
3,3,3,CAN,HEALTHEXP,TOT,USD_CAP,A,2016,5039.601,NaN
4,4,4,CZE,HEALTHEXP,TOT,USD_CAP,A,2016,2670.970,NaN
...,...,...,...,...,...,...,...,...,...,...
427,427,427,CYP,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1489.514,NaN
428,428,428,MLT,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,2425.117,NaN
429,429,429,MLT,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1394.678,NaN
430,430,430,ROU,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,1326.964,NaN
431,431,431,ROU,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,337.332,NaN

In [23]:
DP_LIVE_02_2017_df=DP_LIVE_02_2019_df[DP_LIVE_02 ['TIME']!=2017]
DP_LIVE_02_2017_df

<ipython-input-23-7be65c24dec6>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  DP_LIVE_02_2017_df=DP_LIVE_02_2019_df[DP_LIVE_02 ['TIME']!=2017]

,Unnamed: 0,Unnamed: 0.1,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,0,0,AUS,HEALTHEXP,TOT,USD_CAP,A,2016,4624.966,D
1,1,1,AUT,HEALTHEXP,TOT,USD_CAP,A,2016,5195.531,NaN
2,2,2,BEL,HEALTHEXP,TOT,USD_CAP,A,2016,5003.902,NaN
3,3,3,CAN,HEALTHEXP,TOT,USD_CAP,A,2016,5039.601,NaN
4,4,4,CZE,HEALTHEXP,TOT,USD_CAP,A,2016,2670.970,NaN
...,...,...,...,...,...,...,...,...,...,...
427,427,427,CYP,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1489.514,NaN
428,428,428,MLT,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,2425.117,NaN
429,429,429,MLT,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1394.678,NaN
430,430,430,ROU,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,1326.964,NaN
431,431,431,ROU,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,337.332,NaN

In [24]:
DP_LIVE_02_2016_df=DP_LIVE_02_2017_df[DP_LIVE_02 ['TIME']!=2016]
DP_LIVE_02_2016_df

<ipython-input-24-cf7ddea79467>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  DP_LIVE_02_2016_df=DP_LIVE_02_2017_df[DP_LIVE_02 ['TIME']!=2016]

,Unnamed: 0,Unnamed: 0.1,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
288,288,288,AUS,HEALTHEXP,TOT,USD_CAP,A,2018,4793.460,D
289,289,289,AUT,HEALTHEXP,TOT,USD_CAP,A,2018,5544.767,NaN
290,290,290,BEL,HEALTHEXP,TOT,USD_CAP,A,2018,5358.892,NaN
291,291,291,CAN,HEALTHEXP,TOT,USD_CAP,A,2018,5330.848,NaN
292,292,292,CZE,HEALTHEXP,TOT,USD_CAP,A,2018,3174.386,NaN
...,...,...,...,...,...,...,...,...,...,...
427,427,427,CYP,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1489.514,NaN
428,428,428,MLT,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,2425.117,NaN
429,429,429,MLT,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1394.678,NaN
430,430,430,ROU,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,1326.964,NaN
431,431,431,ROU,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,337.332,NaN

In [26]:
DP_LIVE_02_2016_df["TIME"].unique()

array([2018])

In [27]:
DP_LIVE_02_2016_df["LOCATION"].unique()

array(['AUS', 'AUT', 'BEL', 'CAN', 'CZE', 'DNK', 'FIN', 'FRA', 'DEU',
       'GRC', 'HUN', 'ISL', 'IRL', 'ITA', 'JPN', 'KOR', 'LUX', 'MEX',
       'NLD', 'NZL', 'NOR', 'POL', 'PRT', 'SVK', 'ESP', 'SWE', 'CHE',
       'TUR', 'GBR', 'USA', 'CHL', 'EST', 'ISR', 'SVN', 'CHN', 'COL',
       'IND', 'IDN', 'LVA', 'LTU', 'RUS', 'ZAF', 'CRI', 'BGR', 'HRV',
       'CYP', 'MLT', 'ROU'], dtype=object)

In [30]:
COUNTRIES = ["AUS","CAN","FRA","IRL","MEX","NOR","BEL","FIN","JPN","KOR"]
DP_LIVE_02_countries_df=DP_LIVE_02_2016_df[DP_LIVE_02_df['LOCATION'].isin(COUNTRIES)]
DP_LIVE_02_countries_df

<ipython-input-30-d02eb59de148>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  DP_LIVE_02_countries_df=DP_LIVE_02_2016_df[DP_LIVE_02_df['LOCATION'].isin(COUNTRIES)]

,Unnamed: 0,Unnamed: 0.1,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
288,288,288,AUS,HEALTHEXP,TOT,USD_CAP,A,2018,4793.460,D
290,290,290,BEL,HEALTHEXP,TOT,USD_CAP,A,2018,5358.892,NaN
291,291,291,CAN,HEALTHEXP,TOT,USD_CAP,A,2018,5330.848,NaN
294,294,294,FIN,HEALTHEXP,TOT,USD_CAP,A,2018,4379.886,NaN
295,295,295,FRA,HEALTHEXP,TOT,USD_CAP,A,2018,5136.200,NaN
300,300,300,IRL,HEALTHEXP,TOT,USD_CAP,A,2018,4897.590,NaN
302,302,302,JPN,HEALTHEXP,TOT,USD_CAP,A,2018,4558.669,NaN
303,303,303,KOR,HEALTHEXP,TOT,USD_CAP,A,2018,3091.826,NaN
305,305,305,MEX,HEALTHEXP,TOT,USD_CAP,A,2018,1116.032,NaN
308,308,308,NOR,HEALTHEXP,TOT,USD_CAP,A,2018,6536.761,NaN
336,336,336,AUS,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,3192.682,D
337,337,337,AUS,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1600.779,D
340,340,340,BEL,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,4118.526,NaN
341,341,341,BEL,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1240.366,NaN
342,342,342,CAN,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,3740.630,NaN
343,343,343,CAN,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1590.218,NaN
348,348,348,FIN,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,3368.898,NaN
349,349,349,FIN,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1010.988,NaN
350,350,350,FRA,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,4289.553,NaN
351,351,351,FRA,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,846.647,NaN
360,360,360,IRL,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,3630.391,NaN
361,361,361,IRL,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1267.200,NaN
364,364,364,JPN,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,3818.840,NaN
365,365,365,JPN,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,739.829,NaN
366,366,366,KOR,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,1857.071,NaN
367,367,367,KOR,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1234.755,NaN
370,370,370,MEX,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,554.384,NaN
371,371,371,MEX,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,561.648,NaN
376,376,376,NOR,HEALTHEXP,COMPULSORY,USD_CAP,A,2018,5602.233,NaN
377,377,377,NOR,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,934.528,NaN

In [31]:
DP_LIVE_02_subjects_df=DP_LIVE_02_countries_df[DP_LIVE_02 ['SUBJECT']!='COMPULSORY']
DP_LIVE_02_subjects_df

<ipython-input-31-4c6d2fdb1e94>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  DP_LIVE_02_subjects_df=DP_LIVE_02_countries_df[DP_LIVE_02 ['SUBJECT']!='COMPULSORY']

,Unnamed: 0,Unnamed: 0.1,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
288,288,288,AUS,HEALTHEXP,TOT,USD_CAP,A,2018,4793.460,D
290,290,290,BEL,HEALTHEXP,TOT,USD_CAP,A,2018,5358.892,NaN
291,291,291,CAN,HEALTHEXP,TOT,USD_CAP,A,2018,5330.848,NaN
294,294,294,FIN,HEALTHEXP,TOT,USD_CAP,A,2018,4379.886,NaN
295,295,295,FRA,HEALTHEXP,TOT,USD_CAP,A,2018,5136.200,NaN
300,300,300,IRL,HEALTHEXP,TOT,USD_CAP,A,2018,4897.590,NaN
302,302,302,JPN,HEALTHEXP,TOT,USD_CAP,A,2018,4558.669,NaN
303,303,303,KOR,HEALTHEXP,TOT,USD_CAP,A,2018,3091.826,NaN
305,305,305,MEX,HEALTHEXP,TOT,USD_CAP,A,2018,1116.032,NaN
308,308,308,NOR,HEALTHEXP,TOT,USD_CAP,A,2018,6536.761,NaN
337,337,337,AUS,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1600.779,D
341,341,341,BEL,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1240.366,NaN
343,343,343,CAN,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1590.218,NaN
349,349,349,FIN,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1010.988,NaN
351,351,351,FRA,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,846.647,NaN
361,361,361,IRL,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1267.200,NaN
365,365,365,JPN,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,739.829,NaN
367,367,367,KOR,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,1234.755,NaN
371,371,371,MEX,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,561.648,NaN
377,377,377,NOR,HEALTHEXP,VOLUNTARY,USD_CAP,A,2018,934.528,NaN

In [32]:
DP_LIVE_02_vol_df=DP_LIVE_02_subjects_df[DP_LIVE_02 ['SUBJECT']!='VOLUNTARY']
DP_LIVE_02_vol_df

<ipython-input-32-f32c12fdfcfe>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  DP_LIVE_02_vol_df=DP_LIVE_02_subjects_df[DP_LIVE_02 ['SUBJECT']!='VOLUNTARY']

,Unnamed: 0,Unnamed: 0.1,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
288,288,288,AUS,HEALTHEXP,TOT,USD_CAP,A,2018,4793.460,D
290,290,290,BEL,HEALTHEXP,TOT,USD_CAP,A,2018,5358.892,NaN
291,291,291,CAN,HEALTHEXP,TOT,USD_CAP,A,2018,5330.848,NaN
294,294,294,FIN,HEALTHEXP,TOT,USD_CAP,A,2018,4379.886,NaN
295,295,295,FRA,HEALTHEXP,TOT,USD_CAP,A,2018,5136.200,NaN
300,300,300,IRL,HEALTHEXP,TOT,USD_CAP,A,2018,4897.590,NaN
302,302,302,JPN,HEALTHEXP,TOT,USD_CAP,A,2018,4558.669,NaN
303,303,303,KOR,HEALTHEXP,TOT,USD_CAP,A,2018,3091.826,NaN
305,305,305,MEX,HEALTHEXP,TOT,USD_CAP,A,2018,1116.032,NaN
308,308,308,NOR,HEALTHEXP,TOT,USD_CAP,A,2018,6536.761,NaN

In [33]:
DP_LIVE_02_vol_df.to_csv('DP_LIVE_02_vol_df.csv')