In [4]:
import pandas as pd

In [6]:
DP_LIVE_02 = pd.read_csv("DP_LIVE_02.csv")

In [7]:
DP_LIVE_02.head(10)

  LOCATION  INDICATOR SUBJECT  MEASURE FREQUENCY  TIME     Value Flag Codes
0      AUS  HEALTHEXP     TOT  USD_CAP         A  2016  4624.966          D
1      AUT  HEALTHEXP     TOT  USD_CAP         A  2016  5195.531        NaN
2      BEL  HEALTHEXP     TOT  USD_CAP         A  2016  5003.902        NaN
3      CAN  HEALTHEXP     TOT  USD_CAP         A  2016  5039.601        NaN
4      CZE  HEALTHEXP     TOT  USD_CAP         A  2016  2670.970        NaN
5      DNK  HEALTHEXP     TOT  USD_CAP         A  2016  4849.758        NaN
6      FIN  HEALTHEXP     TOT  USD_CAP         A  2016  4103.556        NaN
7      FRA  HEALTHEXP     TOT  USD_CAP         A  2016  4922.263        NaN
8      DEU  HEALTHEXP     TOT  USD_CAP         A  2016  5670.578        NaN
9      GRC  HEALTHEXP     TOT  USD_CAP         A  2016  2220.862        NaN

In [8]:
DP_LIVE_02_not_2020 = DP_LIVE_02[DP_LIVE_02['TIME']!=2020]
DP_LIVE_02_not_2020.head(100)

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,HEALTHEXP,TOT,USD_CAP,A,2016,4624.966,D
1,AUT,HEALTHEXP,TOT,USD_CAP,A,2016,5195.531,NaN
2,BEL,HEALTHEXP,TOT,USD_CAP,A,2016,5003.902,NaN
3,CAN,HEALTHEXP,TOT,USD_CAP,A,2016,5039.601,NaN
4,CZE,HEALTHEXP,TOT,USD_CAP,A,2016,2670.970,NaN
...,...,...,...,...,...,...,...,...
95,SVK,HEALTHEXP,VOLUNTARY,USD_CAP,A,2016,400.572,NaN
96,ESP,HEALTHEXP,COMPULSORY,USD_CAP,A,2016,2252.883,NaN
97,ESP,HEALTHEXP,VOLUNTARY,USD_CAP,A,2016,895.701,NaN
98,SWE,HEALTHEXP,COMPULSORY,USD_CAP,A,2016,4320.614,NaN
99,SWE,HEALTHEXP,VOLUNTARY,USD_CAP,A,2016,806.961,NaN

In [9]:
DP_LIVE_02_not_2020["TIME"].unique()

array([2016, 2017, 2018, 2019])

In [10]:
DP_LIVE_02_not_2020["LOCATION"].unique()

array(['AUS', 'AUT', 'BEL', 'CAN', 'CZE', 'DNK', 'FIN', 'FRA', 'DEU',
       'GRC', 'HUN', 'ISL', 'IRL', 'ITA', 'JPN', 'KOR', 'LUX', 'MEX',
       'NLD', 'NZL', 'NOR', 'POL', 'PRT', 'SVK', 'ESP', 'SWE', 'CHE',
       'TUR', 'GBR', 'USA', 'CHL', 'EST', 'ISR', 'SVN', 'CHN', 'COL',
       'IND', 'IDN', 'LVA', 'LTU', 'RUS', 'ZAF', 'CRI', 'BGR', 'HRV',
       'CYP', 'MLT', 'ROU'], dtype=object)

In [11]:
COUNTRIES = ["AUS","CAN","FRA","IRL","MEX","NOR","BEL","FIN","JPN","KOR"]
DP_LIVE_02_not_2020[DP_LIVE_02_not_2020['LOCATION'].isin(COUNTRIES)]

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUS,HEALTHEXP,TOT,USD_CAP,A,2016,4624.966,D
2,BEL,HEALTHEXP,TOT,USD_CAP,A,2016,5003.902,NaN
3,CAN,HEALTHEXP,TOT,USD_CAP,A,2016,5039.601,NaN
6,FIN,HEALTHEXP,TOT,USD_CAP,A,2016,4103.556,NaN
7,FRA,HEALTHEXP,TOT,USD_CAP,A,2016,4922.263,NaN
...,...,...,...,...,...,...,...,...
506,KOR,HEALTHEXP,VOLUNTARY,USD_CAP,A,2019,1329.092,NaN
509,MEX,HEALTHEXP,COMPULSORY,USD_CAP,A,2019,558.640,NaN
510,MEX,HEALTHEXP,VOLUNTARY,USD_CAP,A,2019,574.326,NaN
514,NOR,HEALTHEXP,COMPULSORY,USD_CAP,A,2019,5788.239,NaN
515,NOR,HEALTHEXP,VOLUNTARY,USD_CAP,A,2019,956.383,NaN

In [16]:
DP_LIVE_02.to_csv('DP_LIVE_02.csv')